# Tensors

Tensors are specialized data structure that are very similar to arrays and matrices, in pytorch we use tensors to encode the inputs and outputs of a model, as well as model parameters.

Tensors are similar ot NumPy's ndarrays, except that tensors can run on GPU or other hardware accelerators. in fact, tensors an numpy arrays can often share the sam underlying memory, eliminating he need ti copy data. Tensors are also optimized for automatic differentiation. 

In [1]:
import torch
import numpy as np


In [2]:
# Tensor initialization
# Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
# from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# from another tensor
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(f"random Tensor: \n {x_rand}\n")

random Tensor: 
 tensor([[0.3165, 0.5446],
        [0.3925, 0.0718]])



In [5]:
# tensors can be defined with random or constant values

shape = (2, 3, )

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [6]:
# Tensor has 3 basic attributes

tensor = torch.rand(3,4)


print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations

There are over 100 different tensor operations available in PyTorch. They include arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling ... 

Each of these operations can be run on the GPU. By default tensors are created on the CPU. Tensors needs to be explicitly move to GPU using `.to` method (after checking for GPU availability). Keep in mind that copying large tesors across devices can be expensive in terms of time and memory.


In [7]:
# Be advised: other notebook kernels that use GPU need to be closed
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [8]:
# tensor API is  very simiral to numpy
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# to join multiple tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
# arithmetic operations

# matrix multiplication between two tensors
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# elementwise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [11]:
# single-element tensors conversion to python value
agg = tensor.sum()
agg_item = agg.item()
print(agg, type(agg))
print(agg_item, type(agg_item))

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


In [12]:
# In place operations

print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridging with Numpy
tensors on CPU and numpy arrays can share their underliying memory locations adn changing one will change the other.

In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [14]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [15]:
# same goes vice versa
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
